var mongoose = require('mongoose');
var Promise = require('bluebird');
var Connection = Promise.promisifyAll(mongoose.model('Connection'));

var seedConnections = function () {
  var connections = [
    { cityNames: ['New York', 'Boston'], distance: 3 },
    { cityNames: ['New York', 'Philadelphia'], distance: 0},
    { cityNames: ['New York', 'Buffalo'], distance: 8 },
    { cityNames: ['Pittsburgh', 'Buffalo'], distance: 7 },
    { cityNames: ['Washington, D.C.', 'Philadelphia'], distance: 3 },
    { cityNames: ['Pittsburgh', 'Washington, D.C.'], distance: 6 },
    { cityNames: ['Norfolk', 'Washington, D.C.'], distance: 5 },
    { cityNames: ['Raleigh', 'Norfolk'], distance: 3 },
    { cityNames: ['Raleigh', 'Pittsburgh'], distance: 7 },
    { cityNames: ['Detroit', 'Buffalo'], distance: 7 },
    { cityNames: ['Detroit', 'Pittsburgh'], distance: 6 },
    { cityNames: ['Detroit', 'Duluth'], distance: 15 },
    { cityNames: ['Detroit', 'Chicago'], distance:7 },
    { cityNames: ['Detroit', 'Cincinnati'], distance:4 },
    { cityNames: ['Pittsburgh', 'Cincinnati'], distance: 7 },
    { cityNames: ['Cincinnati', 'Raleigh'], distance: 15 },
    { cityNames: ['Cincinnati', 'Knoxville'], distance: 6 },
    { cityNames: ['Cincinnati', 'Chicago'], distance: 7 },
    { cityNames: ['Cincinnati', 'St. Louis'], distance:12 },
    { cityNames: ['Knoxville', 'Atlanta'], distance: 5 },
    { cityNames: ['Atlanta', 'Raleigh'], distance: 7 },
    { cityNames: ['Raleigh', 'Savannah'], distance:7 },
    { cityNames: ['Atlanta', 'Savannah'], distance: 7 },
    { cityNames: ['Savannah', 'Jacksonville'], distance:0 },
    { cityNames: ['Jacksonville', 'Tampa'], distance: 4 },
    { cityNames: ['Tampa', 'Miami'], distance: 4 },
    { cityNames: ['Atlanta', 'Birmingham'], distance:3 },
    { cityNames: ['Atlanta', 'St. Louis'], distance:12 },
    { cityNames: ['Jacksonville', 'Birmingham'], distance:9 },
    { cityNames: ['Jacksonville', 'New Orleans'], distance:16 },
    { cityNames: ['Birmingham', 'New Orleans'], distance:11 },
    { cityNames: ['Birmingham', 'Memphis'], distance: 6},
    { cityNames: ['New Orleans', 'Memphis'], distance: 7 },
    { cityNames: ['New Orleans', 'Houston'], distance:8 },
    { cityNames: ['New Orleans', 'Dallas'], distance: 12 },
    { cityNames: ['Memphis', 'Dallas'], distance:12 },
    { cityNames: ['Memphis', 'Oklahoma City'], distance:14 },
    { cityNames: ['Memphis', 'Kansas City'], distance:12 },
    { cityNames: ['Memphis', 'St. Louis'], distance:7 },
    { cityNames: ['Chicago', 'St. Louis'], distance:10 },
    { cityNames: ['St. Louis', 'Kansas City'], distance:6 },
    { cityNames: ['Chicago', 'Kansas City'], distance:8 },
    { cityNames: ['Chicago', 'Omaha'], distance:13 },
    { cityNames: ['Chicago', 'Minneapolis'], distance:8 },
    { cityNames: ['Chicago', 'Duluth'], distance:12 },
    { cityNames: ['Duluth', 'Minneapolis'], distance:5 },
    { cityNames: ['Duluth', 'Fargo'], distance:6 },
    { cityNames: ['Fargo', 'Minneapolis'], distance:6 },
    { cityNames: ['Omaha', 'Minneapolis'], distance:8 },
    { cityNames: ['Omaha', 'Kansas City'], distance:5 },
    { cityNames: ['Kansas City', 'Oklahoma City'], distance:8 },
    { cityNames: ['Oklahoma City', 'Dallas'], distance:3 },
    { cityNames: ['Dallas', 'Houston'], distance:5 },
    { cityNames: ['Fargo', 'Billings'], distance:17 },
    { cityNames: ['Billings', 'Minneapolis'], distance:18 },
    { cityNames: ['Minneapolis', 'Cheyenne'], distance:18 },
    { cityNames: ['Omaha', 'Cheyenne'], distance:14 },
    { cityNames: ['Denver', 'Kansas City'], distance:16 },
    { cityNames: ['Santa Fe', 'Kansas City'], distance:16 },
    { cityNames: ['Oklahoma City', 'Santa Fe'], distance:15 },
    { cityNames: ['Dallas', 'Santa Fe'], distance:16 },
    { cityNames: ['Houston', 'Santa Fe'], distance:21 },
    { cityNames: ['Denver', 'Santa Fe'], distance: 13 },
    { cityNames: ['Cheyenne', 'Denver'], distance:0 },
    { cityNames: ['Billings', 'Cheyenne'], distance:9 },
    { cityNames: ['Salt Lake City', 'Santa Fe'], distance:28 },
    { cityNames: ['Salt Lake City', 'Denver'], distance:21 },
    { cityNames: ['Salt Lake City', 'Boise'], distance:8 },
    { cityNames: ['Salt Lake City', 'San Francisco'], distance:27 },
    { cityNames: ['Salt Lake City', 'Las Vegas'], distance:18 },
    { cityNames: ['Santa Fe', 'Phoenix'], distance:18 },
    { cityNames: ['Santa Fe', 'Las Vegas'], distance: 27},
    { cityNames: ['Las Vegas', 'Phoenix'], distance: 15 },
    { cityNames: ['Cheyenne', 'Boise'], distance:21 },
    { cityNames: ['Billings', 'Boise'], distance:12 },
    { cityNames: ['Seattle', 'Billings'], distance:9 },
    { cityNames: ['Seattle', 'Boise'], distance:12 },
    { cityNames: ['Boise', 'Portland'] , distance:13},
    { cityNames: ['Seattle', 'Portland'], distance:3 },
    { cityNames: ['Boise', 'San Francisco'], distance:23 },
    { cityNames: ['Portland', 'San Francisco'], distance:24 },
    { cityNames: ['Las Vegas', 'San Francisco'], distance: 14},
    { cityNames: ['Las Vegas', 'Los Angeles'], distance:9 },
    { cityNames: ['San Francisco', 'Los Angeles'], distance:9 },
    { cityNames: ['Los Angeles', 'San Diego'], distance:3 },
    { cityNames: ['Phoenix', 'San Diego'], distance:14 },
    { cityNames: ['Las Vegas', 'San Diego'], distance:9 },

    { cityNames: ['Flensburg', 'Kiel'], distance:4 },
    { cityNames: ['Kiel', 'Lubeck'], distance:4 },
    { cityNames: ['Kiel', 'Hamburg'], distance:8 },
    { cityNames: ['Hamburg', 'Cuxhaven'], distance:11 },
    { cityNames: ['Hamburg', 'Bremen'], distance:11 },
    { cityNames: ['Hamburg', 'Lubeck'], distance:6 },
    { cityNames: ['Hamburg', 'Schwerin'], distance:8 },
    { cityNames: ['Hamburg', 'Hannover'], distance:17 },
    { cityNames: ['Cuxhaven', 'Bremen'], distance:8 },
    { cityNames: ['Wilhelmshaven', 'Bremen'], distance:11 },
    { cityNames: ['Wilhelmshaven', 'Osnabruck'], distance:14 },
    { cityNames: ['Bremen', 'Hannover'], distance:10 },
    { cityNames: ['Bremen', 'Osnabruck'], distance:11 },
    { cityNames: ['Hannover', 'Schwerin'], distance:19 },
    { cityNames: ['Hannover', 'Magdeberg'], distance:15 },
    { cityNames: ['Hannover', 'Osnabruck'], distance:16 },
    { cityNames: ['Hannover', 'Kassel'], distance:15 },
    { cityNames: ['Hannover', 'Erfurt'], distance:19 },
    { cityNames: ['Osnabruck', 'Kassel'], distance:20 },
    { cityNames: ['Osnabruck', 'Munster'], distance:7 },
    { cityNames: ['Munster', 'Essen'], distance:6 },
    { cityNames: ['Munster', 'Dortmund'], distance:2 },
    { cityNames: ['Essen', 'Duisburg'], distance:0 },
    { cityNames: ['Essen', 'Dusseldorf'], distance:2 },
    { cityNames: ['Essen', 'Dortmund'], distance:4 },
    { cityNames: ['Dortmund', 'Kassel'], distance:18 },
    { cityNames: ['Dortmund', 'Frankfurt'], distance:20 },
    { cityNames: ['Dortmund', 'Koln'], distance:10 },
    { cityNames: ['Dusseldorf', 'Aachen'], distance:9 },
    { cityNames: ['Dusseldorf', 'Koln'], distance:4 },
    { cityNames: ['Aachen', 'Koln'], distance:7 },
    { cityNames: ['Aachen', 'Trier'], distance:19 },
    { cityNames: ['Trier', 'Koln'], distance:20 },
    { cityNames: ['Trier', 'Wiesbaden'], distance:18 },
    { cityNames: ['Trier', 'Saarbrucken'], distance:11 },
    { cityNames: ['Wiesbaden', 'Saarbrucken'], distance:10 },
    { cityNames: ['Wiesbaden', 'Frankfurt'], distance:0 },
    { cityNames: ['Wiesbaden', 'Koln'], distance:21 },
    { cityNames: ['Wiesbaden', 'Mannheim'], distance:11 },
    { cityNames: ['Saarbrucken', 'Mannheim'], distance:11 },
    { cityNames: ['Saarbrucken', 'Stuttgart'], distance:17 },
    { cityNames: ['Stuttgart', 'Mannheim'], distance:6 },
    { cityNames: ['Stuttgart', 'Freiburg'], distance:16 },
    { cityNames: ['Stuttgart', 'Konstanz'], distance:16 },
    { cityNames: ['Stuttgart', 'Wurzburg'], distance:12 },
    { cityNames: ['Stuttgart', 'Augsburg'], distance:15 },
    { cityNames: ['Freiburg', 'Konstanz'], distance:14 },
    { cityNames: ['Augsburg', 'Konstanz'], distance:17 },
    { cityNames: ['Augsburg', 'Wurzburg'], distance:19 },
    { cityNames: ['Augsburg', 'Munchen'], distance:6 },
    { cityNames: ['Augsburg', 'Regensberg'], distance:13 },
    { cityNames: ['Augsburg', 'Nurnburg'], distance:18 },
    { cityNames: ['Passau', 'Munchen'], distance:14 },
    { cityNames: ['Passau', 'Regensberg'], distance:12 },
    { cityNames: ['Munchen', 'Regensberg'], distance:10 },
    { cityNames: ['Nurnburg', 'Regensberg'], distance:12 },
    { cityNames: ['Nurnburg', 'Wurzburg'], distance:8 },
    { cityNames: ['Nurnburg', 'Erfurt'], distance:21 },
    { cityNames: ['Wurzburg', 'Mannheim'], distance:10 },
    { cityNames: ['Wurzburg', 'Frankfurt'], distance:13 },
    { cityNames: ['Wurzburg', 'Fulda'], distance:11 },
    { cityNames: ['Frankfurt', 'Fulda'], distance:8 },
    { cityNames: ['Frankfurt', 'Kassel'], distance:13 },
    { cityNames: ['Fulda', 'Erfurt'], distance:13 },
    { cityNames: ['Fulda', 'Kassel'], distance:8 },
    { cityNames: ['Erfurt', 'Kassel'], distance:15 },
    { cityNames: ['Erfurt', 'Halle'], distance:6 },
    { cityNames: ['Erfurt', 'Dresden'], distance:19 },
    { cityNames: ['Frankfurt an der Oder', 'Dresden'], distance:16 },
    { cityNames: ['Frankfurt an der Oder', 'Leipzig'], distance:21 },
    { cityNames: ['Frankfurt an der Oder', 'Berlin'], distance:6 },
    { cityNames: ['Dresden', 'Leipzig'], distance:13 },
    { cityNames: ['Halle', 'Leipzig'], distance:0 },
    { cityNames: ['Halle', 'Berlin'], distance:17 },
    { cityNames: ['Halle', 'Magdeberg'], distance:11 },
    { cityNames: ['Berlin', 'Torgelow'], distance:15 },
    { cityNames: ['Berlin', 'Magdeberg'], distance:10 },
    { cityNames: ['Berlin', 'Schwerin'], distance:18 },
    { cityNames: ['Schwerin', 'Magdeberg'], distance:16 },
    { cityNames: ['Schwerin', 'Torgelow'], distance:19 },
    { cityNames: ['Schwerin', 'Lubeck'], distance:6 },
    { cityNames: ['Schwerin', 'Rostock'], distance:6 },
    { cityNames: ['Torgelow', 'Rostock'], distance:19 },
  ];

  return Promise.each(connections, function (connection) { return Connection. create(connection); });
};

module.exports = seedConnections;